on:
  push:
    branches:
      - production
name: ğŸš€ Deploy production Mountain on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy Dev Mountain
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2.3.2

      - name: ğŸ”¨ Build Project
        run: |
          npm install
          gulp compile:sass

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.production_server_ip }}
          username: ${{ secrets.prod_mountain_username }}
          password: ${{ secrets.prod_mountain_password }}
          server-dir: /public/wp-content/themes/sbh_center_3.2/
