on:
  push:
    branches:
      - dev
name: ğŸš€ Deploy Dev Mountain on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy Dev Mountain
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2.3.2

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.dev.mountainspringsrecovery.com
          username: ${{ secrets.dev_ftp_username }}
          password: ${{ secrets.dev_ftp_password }}
          server-dir: /public_html/wp-content/themes/sbh_center_3.2/
